
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY . . 

COPY wait-for-it.sh /app/
RUN chmod +x /app/wait-for-it.sh

RUN dotnet publish -c Release -o /out

RUN ls -la /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /out .

COPY wait-for-it.sh /app/
RUN chmod +x /app/wait-for-it.sh

ENTRYPOINT ["./wait-for-it.sh", "db:1433", "--", "dotnet", "CorteosTestTask.dll"]
